"""added exercises and sets

Revision ID: 99dc36edc5f1
Revises: 203ffc7c66e6
Create Date: 2024-02-17 00:39:06.158947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99dc36edc5f1"
down_revision: Union[str, None] = "203ffc7c66e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Float(), server_default="0", nullable=True),
        sa.Column("units", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("repetitions", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "performed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("weight", sa.Float(), nullable=True))
    op.add_column("workouts", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column(
        "workouts",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "workouts", sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "workouts", sa.Column("average_time_resting", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "workouts", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("workouts_user_id_fkey", "workouts", type_="foreignkey")
    op.drop_column("workouts", "average_time_resting")
    op.drop_column("workouts", "ended_at")
    op.drop_column("workouts", "created_at")
    op.drop_column("workouts", "user_id")
    op.drop_column("users", "weight")
    op.drop_table("set")
    op.drop_table("exercises")
    # ### end Alembic commands ###
